# Configuration for Persistent Graph Memory System

# --- File Paths ---
base_memory_path: "memory_sets"
data_dir: "memory_data"
workspace_dir: "Workspace" # Subdirectory within data_dir
calendar_file: "calendar.jsonl" # Filename for calendar within workspace

# Default personality folder name (used if none selected)
default_personality: "default"

# --- Models & API ---
embedding_model: "all-MiniLM-L6-v2"
tokenizer_name: "google/gemma-7b-it"
kobold_api_url: "http://localhost:5001/api/v1/generate"

# --- Feature Flags ---
features:
  enable_saliency: true # Enable/disable saliency calculations
  enable_emotion_analysis: true # Enable/disable basic emotion analysis during consolidation
  enable_forgetting: true # Enable/disable nuanced forgetting
  enable_rich_associations: true # Enable/disable LLM-based rich association extraction (Phase 1.1+)

# --- Activation Spreading Parameters ---
activation:
  initial: 1.0
  threshold: 0.1
  node_decay_rate: 0.02
  edge_decay_rate: 0.01
  spreading_depth: 3
  max_initial_nodes: 7
  propagation_factor_base: 0.7
  propagation_factors:
    TEMPORAL_fwd: 1.0
    TEMPORAL_bwd: 0.8
    SUMMARY_OF_fwd: 1.2
    SUMMARY_OF_bwd: 0.4
    MENTIONS_CONCEPT_fwd: 1.0
    MENTIONS_CONCEPT_bwd: 0.9
    ASSOCIATIVE: 0.8
    HIERARCHICAL_fwd: 1.1
    HIERARCHICAL_bwd: 0.5
    UNKNOWN: 0.5

# --- Prompting & Context Configuration ---
prompting:
  max_context_tokens: 8192 # Corrected the float value to integer
  context_headroom: 250
  memory_budget_ratio: 0.45
  history_budget_ratio: 0.55

# --- Consolidation Parameters ---
consolidation:
  turn_count: 10
  min_nodes: 5
  concept_similarity_threshold: 0.3

# --- Emotion Analysis ---
emotion_analysis:
  default_valence: 0.0 # Neutral
  default_arousal: 0.1 # Slightly above baseline minimum arousal

# --- Forget Topic ---
forget_topic:
  similarity_k: 15

# --- Nuanced Forgetting ---
forgetting:
  trigger_interaction_count: 20 # How often to run maintenance (0 to disable)
  score_threshold: 0.7 # Score above which nodes get archived
  candidate_min_age_hours: 24 # Only consider nodes older than this
  candidate_min_activation: 0.05 # Only consider nodes with low activation
  protected_node_types: ['concept', 'summary'] # Types never automatically forgotten
  # --- Forgettability Score Weights (must sum roughly to 1.0) ---
  weights:
    # Factors increasing forgettability:
    recency_factor: 0.3      # How long since last access (older = more forgettable)
    activation_factor: 0.2   # Low activation = more forgettable
    node_type_factor: 0.1    # e.g., 'turn' nodes are more forgettable than others
    # Factors decreasing forgettability (Resistance):
    saliency_factor: 0.2     # Higher saliency = less forgettable (Placeholder)
    emotion_factor: 0.1      # Higher emotional intensity = less forgettable (Placeholder)
    connectivity_factor: 0.1 # Higher degree = less forgettable (Placeholder)

# --- GUI Keywords --- # Moved from bottom for better grouping
modification_keywords:
  - "forget"
  - "delete"
  - "remove"
  - "edit"
  - "change"
  - "correct"
  - "update"


# --- GUI Style Configuration ---
# (Keep existing style config)
gui_style:
  bubbles:
    max_width_percent: 75
    side_margin_px: 50
    edge_margin_px: 5
    min_width_px: 400
    border_radius_px: 18
    internal_padding_top_bottom_px: 6
    internal_padding_left_right_px: 10
    timestamp_color_user: "#E0E0E0"
    timestamp_color_ai: "#B0B0B0"
    thumbnail_max_width_px: 200
  input_field:
    border_radius_px: 15
    padding_px: 8
  buttons:
    border_radius_px: 15
    padding_vertical_px: 8
    padding_horizontal_px: 16
# --- Saliency Calculation ---
saliency:
  initial_scores: # Base scores by node type
    turn: 0.4
    summary: 0.7
    concept: 0.8
    default: 0.5
  emotion_influence_factor: 0.2 # How much default arousal boosts initial saliency
  activation_influence: 0.1 # How much saliency boosts activation spreading
