# Configuration for Persistent Graph Memory System

# --- File Paths ---
base_memory_path: "memory_sets"
data_dir: "memory_data"
workspace_dir: "Workspace" # Subdirectory within data_dir
calendar_file: "calendar.jsonl" # Filename for calendar within workspace

# Default personality folder name (used if none selected)
default_personality: "default"

# --- Models & API ---
embedding_model: "all-MiniLM-L6-v2"
tokenizer_name: "google/gemma-7b-it"
kobold_api_url: "http://localhost:5001/api/v1/generate" # <<< CHECK AND UPDATE THIS URL based on your KoboldCpp setup

# --- Feature Flags ---
features:
  enable_saliency: true # Enable/disable saliency calculations
  enable_emotion_analysis: true # Enable/disable basic emotion analysis during consolidation
  enable_forgetting: true # Enable/disable nuanced forgetting
  enable_rich_associations: true # Enable/disable LLM-based rich association extraction (Phase 1.1+)

# --- Activation Spreading Parameters ---
activation:
  initial: 0.7 # Reduced from 1.0
  threshold: 0.18 # Increased from 0.1
  node_decay_rate: 0.02
  edge_decay_rate: 0.01
  spreading_depth: 3
  max_initial_nodes: 7
  propagation_factor_base: 0.65 # Reduced from 0.7
  propagation_factors:
    TEMPORAL_fwd: 1.0
    TEMPORAL_bwd: 0.8
    SUMMARY_OF_fwd: 1.2
    SUMMARY_OF_bwd: 0.4
    MENTIONS_CONCEPT_fwd: 1.0
    MENTIONS_CONCEPT_bwd: 0.9
    ASSOCIATIVE: 0.8
    HIERARCHICAL_fwd: 1.1
    HIERARCHICAL_bwd: 0.5
    # --- NEW Relation Types (Add factors for types used in consolidation) ---
    CAUSES: 1.1             # Cause->Effect might be strong forward
    PART_OF: 1.0            # Part->Whole might be standard
    HAS_PROPERTY: 0.9       # Entity->Property might be slightly weaker
    ENABLES: 1.0
    PREVENTS: 1.0           # Contradiction/Prevention might warrant specific handling later
    CONTRADICTS: 1.0
    SUPPORTS: 1.0
    EXAMPLE_OF: 0.9
    MEASURES: 0.9
    LOCATION_OF: 0.9
    ANALOGY: 0.8            # Analogy might be similar to associative
    INFERRED_RELATED_TO: 0.6 # Inferred links should likely be weaker
    SPACY_REL: 0.7          # Generic factor for spaCy-derived relations
    UNKNOWN: 0.5            # Fallback for truly unknown types
  # --- Context Focus ---
  context_focus_boost: 0.15 # Multiplicative boost to initial activation for recently mentioned concepts/turns
  # --- Interference Simulation ---
  interference:
    enable: true
    check_threshold: 0.15 # Activation level above which nodes trigger interference checks
    similarity_threshold: 0.25 # Max FAISS L2 distance for neighbors to interfere (Lower = more similar)
    penalty_factor: 0.90 # Multiplicative factor applied to activation of interfered nodes (e.g., 0.9 reduces activation by 10%)
    max_neighbors_check: 5 # How many nearest neighbors to check for interference
  # --- Emotional Context Bias ---
  emotional_context:
    enable: true
    max_distance: 1.414 # Approx max Euclidean distance in V/A space (-1..1, 0..1 -> sqrt(2^2+1^2) is too high, use sqrt(1^2+1^2))
    boost_factor: 0.1 # Max *additive* boost for emotionally close nodes (applied to act_pass)
    penalty_factor: 0.05 # Max *subtractive* penalty for emotionally distant nodes (applied to act_pass)
    # --- Emotional Reconsolidation on Recall ---
    reconsolidation_enable: true
    reconsolidation_threshold: 0.5 # Min V/A distance to trigger reconsolidation adjustment
    reconsolidation_factor: 0.05 # How much to nudge node emotion towards current mood (0 to 1)

# --- Prompting & Context Configuration ---
prompting:
  max_context_tokens: 8192 # Corrected the float value to integer
  context_headroom: 250
  memory_budget_ratio: 0.45
  history_budget_ratio: 0.55

# --- Consolidation Parameters ---
consolidation:
  trigger_interaction_count: 0 # How often to run consolidation automatically (0 to disable)
  turn_count: 10 # How many turns to process when consolidation runs
  min_nodes: 5 # Minimum suitable nodes required to proceed
  concept_similarity_threshold: 0.3
  # --- Relation Extraction ---
  target_relation_types: # List of relation types the LLM should try to extract
    - "CAUSES"
    - "PART_OF"
    - "HAS_PROPERTY"
    - "RELATED_TO"
    - "IS_A"
    - "ENABLES"
    - "PREVENTS"
    - "CONTRADICTS"
    - "SUPPORTS"
    - "EXAMPLE_OF"
    - "MEASURES"
    - "LOCATION_OF"
  enable_causal_chains: true # Enable/disable causal chain extraction during consolidation
  enable_analogies: true # Enable/disable analogy extraction during consolidation
  # --- Second-Order Inference ---
  inference:
    enable: true
    max_depth: 2 # Fixed at 2 for V1 generic relatedness
    strength_factor: 0.3 # Multiplier for inferred edge strength (based on path strengths)

# --- Emotion Analysis ---
emotion_analysis:
  default_valence: 0.0 # Neutral
  default_arousal: 0.1 # Slightly above baseline minimum arousal

# --- Forget Topic ---
forget_topic:
  similarity_k: 15

# --- Nuanced Forgetting ---
forgetting:
  trigger_interaction_count: 20 # Reverted from 5 back to a higher value for normal operation
  score_threshold: 0.7 # Score above which nodes get archived
  candidate_min_age_hours: 24 # Only consider nodes older than this for strength reduction check
  candidate_min_activation: 0.05 # Only consider nodes with low activation for strength reduction check
  # --- Forgettability Score Weights (used to calculate strength reduction) ---
  weights:
    # Factors increasing forgettability score (leading to more strength reduction):
    recency_factor: 0.4      # Increased from 0.3
    activation_factor: 0.3   # Increased from 0.2
    node_type_factor: 0.1    # e.g., 'turn' nodes are more forgettable than others
    # Factors decreasing forgettability (Resistance):
    saliency_factor: 0.15    # Decreased from 0.2
    emotion_factor: 0.1      # Higher emotional intensity = less forgettable (Placeholder)
    connectivity_factor: 0.05 # Decreased from 0.1
    access_count_factor: 0.05 # Added small weight
    # --- Recency Decay Constant (Higher value = faster initial forgetting score component) ---
    recency_decay_constant: 0.000005 # Example value (adjust based on desired time scale, e.g., for seconds)

# --- Memory Strength Parameters ---
memory_strength:
  initial_value: 1.0 # Starting strength for new nodes
  decay_rate: 0.15 # Increased from 0.1 - Factor applied to forgettability score for strength reduction
  purge_threshold: 0.01 # Strength below which nodes are eligible for permanent deletion by purge_weak_nodes
  purge_min_age_days: 60 # Minimum age (in days) before a node below threshold can be purged

# --- GUI Keywords --- # Moved from bottom for better grouping
modification_keywords:
  - "forget"
  - "delete"
  - "remove"
  - "edit"
  - "change"
  - "correct"
  - "update"


# --- GUI Style Configuration ---
# (Keep existing style config)
gui_style:
  bubbles:
    max_width_percent: 75
    side_margin_px: 50
    edge_margin_px: 5
    min_width_px: 400
    border_radius_px: 18
    internal_padding_top_bottom_px: 6
    internal_padding_left_right_px: 10
    timestamp_color_user: "#E0E0E0"
    timestamp_color_ai: "#B0B0B0"
    thumbnail_max_width_px: 200
  input_field:
    border_radius_px: 15
    padding_px: 8
  buttons:
    border_radius_px: 15
    padding_vertical_px: 8
    padding_horizontal_px: 16

# --- Subconscious Drives ---
subconscious_drives:
  enabled: true # Master switch for the drive system
  # --- Short-Term Drive Dynamics ---
  # Define the core drives and their *base* configuration baseline (before long-term influence)
  base_drives: # Renamed from core_drives for clarity
    Connection: 0.1 # Base need for connection
    Safety: 0.2     # Base need for safety/predictability
    Understanding: 0.1 # Baseline drive to understand
    Novelty: 0.05   # Slight baseline drive for new things
    Control: 0.1    # Base drive for agency/control
  # Parameters for short-term drive updates (based on recent interactions)
  short_term_update_interval_interactions: 10 # How often to potentially update short-term drives via LLM
  short_term_decay_rate: 0.05 # How quickly short-term activation returns towards dynamic baseline (0=no decay)
  short_term_satisfaction_factor: 0.1 # How much satisfaction reduces short-term drive activation
  short_term_frustration_factor: 0.15 # How much frustration increases short-term drive activation

  # --- Long-Term Drive Dynamics ---
  long_term_update_interval_consolidations: 5 # How many consolidations before updating long-term drives (0=disable)
  long_term_adjustment_factor: 0.05 # How much LLM analysis nudges long-term drives (0-1 scale)
  long_term_influence_on_baseline: 1.0 # Multiplier for how much long-term drives affect short-term baseline (0=none, 1=direct addition)

  # --- Mood Influence (Based on Short-Term Drive Deviation from Dynamic Baseline) ---
  mood_influence:
    # How much short-term drive activation *deviation from the dynamic baseline* influences valence/arousal (V/A)
    # Example: High unmet 'Safety' might increase arousal and decrease valence
    # Format: drive_name: [valence_factor, arousal_factor]
    # Positive factor = increases V/A, Negative factor = decreases V/A
    # Factors are multiplied by the drive's current *deviation* (short_term_activation - dynamic_baseline)
    valence_factors:
      Connection: 0.1  # High unmet connection need slightly increases positive valence pull
      Safety: -0.2     # High unmet safety need strongly decreases valence pull (more negative)
      Understanding: 0.05
      Novelty: 0.05
      Control: -0.1    # High control need slightly decreases valence pull
    arousal_factors:
      Connection: 0.05 # High connection need slightly increases arousal
      Safety: 0.3      # High safety need strongly increases arousal
      Understanding: 0.1
      Novelty: 0.15    # High novelty need increases arousal
      Control: 0.2     # High control need increases arousal
    max_mood_adjustment: 0.3 # Maximum absolute change to V or A from drives

# --- Saliency Calculation ---
saliency:
  initial_scores: # Base scores by node type
    turn: 0.4
    summary: 0.7
    concept: 0.8
    intention: 0.75 # NEW: Saliency for intention nodes
    default: 0.5
  emotion_influence_factor: 0.2 # How much default arousal boosts initial saliency
  activation_influence: 0.1 # How much saliency boosts activation spreading
  guaranteed_saliency_threshold: 0.85 # Nodes above this saliency are always included in retrieval if reached
  recall_boost_factor: 0.05 # Additive boost to saliency score upon successful recall (clamped 0-1)
  feedback_factor: 0.15 # Multiplicative factor for user feedback adjustment (e.g., 1.15 to increase, 1/1.15 to decrease)
