# Configuration for Persistent Graph Memory System

# --- File Paths ---
base_memory_path: "memory_sets"
data_dir: "memory_data"
workspace_dir: "Workspace" # Subdirectory within data_dir
calendar_file: "calendar.jsonl" # Filename for calendar within workspace

# Default personality folder name (used if none selected)
default_personality: "default"

# --- Models & API ---
embedding_model: "all-MiniLM-L6-v2"
tokenizer_name: "google/gemma-7b-it"
kobold_api_url: "http://localhost:5001/api/v1/generate"

# --- Activation Spreading Parameters ---
activation:
  initial: 1.0
  threshold: 0.1
  node_decay_rate: 0.02
  edge_decay_rate: 0.01
  spreading_depth: 3
  max_initial_nodes: 7
  propagation_factor_base: 0.7
  propagation_factors:
    TEMPORAL_fwd: 1.0
    TEMPORAL_bwd: 0.8
    SUMMARY_OF_fwd: 1.2
    SUMMARY_OF_bwd: 0.4
    MENTIONS_CONCEPT_fwd: 1.0
    MENTIONS_CONCEPT_bwd: 0.9
    ASSOCIATIVE: 0.8
    HIERARCHICAL_fwd: 1.1
    HIERARCHICAL_bwd: 0.5
    UNKNOWN: 0.5

# --- Prompting & Context Configuration ---
prompting:
  max_context_tokens: 8.192
  context_headroom: 250
  memory_budget_ratio: 0.45
  history_budget_ratio: 0.55

# --- Consolidation Parameters ---
consolidation:
  turn_count: 10
  min_nodes: 5
  # NEW: Threshold for linking to existing concepts (L2 distance, lower=more similar)
  concept_similarity_threshold: 0.3

# --- Forget Topic ---
forget_topic:
  similarity_k: 15

# --- GUI Keywords ---
modification_keywords:
  - "forget"
  - "delete"
  - "remove"
  - "edit"
  - "change"
  - "correct"
  - "update"

# --- GUI Style Configuration ---
gui_style:
  bubbles:
    max_width_percent: 75
    side_margin_px: 50
    edge_margin_px: 5
    min_width_px: 400
    # Removed min_height_px
    border_radius_px: 18
    internal_padding_top_bottom_px: 6  # <<< Maybe try reducing this (e.g., 4) if height is still too much
    internal_padding_left_right_px: 10
    timestamp_color_user: "#E0E0E0"  # <<< ADD: Color for timestamp in user bubble (e.g., light gray/white)
    timestamp_color_ai: "#B0B0B0"    # <<< ADD: Color for timestamp in AI/System bubble (e.g., medium gray)
    thumbnail_max_width_px: 200 # <<< ADD: Max width for image thumbnails
  input_field:
    border_radius_px: 15
    padding_px: 8
  buttons:
    border_radius_px: 15
    padding_vertical_px: 8
    padding_horizontal_px: 16